"""Utilitários compartilhados pelos tabs Gradio."""

from app.interfaces.gradio.utils.i18n import (
    get_language,
    set_language,
    supported_languages,
    t,
)
from app.interfaces.gradio.utils.notifications import (
    ActionableError,
    CommonErrors,
    Notification,
    NotifyLevel,
    clear_history,
    get_history,
    get_unread_count,
    mark_all_read,
    notify,
    notify_critical,
    notify_from_actionable,
    notify_success,
    notify_warning,
    render_notification_center_html,
)
from app.interfaces.gradio.utils.plotting import (
    PLOT_ACCENT,
    PLOT_ACCENT2,
    PLOT_BG,
    PLOT_DANGER,
    PLOT_FACE,
    PLOT_GRID,
    PLOT_SUCCESS,
    PLOT_TEXT,
    PLOT_TEXT_MUTED,
    PLOT_WARNING,
    close_all_figures,
    close_fig,
    confirm_destructive,
    get_service_lock,
    make_figure,
    notify_error,
    notify_info,
    safe_tight_layout,
    style_ax,
    style_legend,
)

__all__ = [
    # Plotting
    "PLOT_ACCENT",
    "PLOT_ACCENT2",
    "PLOT_BG",
    "PLOT_DANGER",
    "PLOT_FACE",
    "PLOT_GRID",
    "PLOT_SUCCESS",
    "PLOT_TEXT",
    "PLOT_TEXT_MUTED",
    "PLOT_WARNING",
    "close_all_figures",
    "close_fig",
    "confirm_destructive",
    "get_service_lock",
    "make_figure",
    "safe_tight_layout",
    "style_ax",
    "style_legend",
    # i18n
    "get_language",
    "set_language",
    "supported_languages",
    "t",
    # Notifications (sistema unificado — 5 níveis)
    "ActionableError",
    "CommonErrors",
    "Notification",
    "NotifyLevel",
    "clear_history",
    "get_history",
    "get_unread_count",
    "mark_all_read",
    "notify",
    "notify_critical",
    "notify_error",
    "notify_from_actionable",
    "notify_info",
    "notify_success",
    "notify_warning",
    "render_notification_center_html",
]
